use_frameworks!

platform :ios, '8.0'

target 'PXPersonPrefenceKit_Example' do
  pod 'PXPersonPrefenceKit', :path => '../'

  target 'PXPersonPrefenceKit_Tests' do
    inherit! :search_paths

    
  end
end
